### ISSUE TITLE
Explore using Athame or similar approach for Vi bindings

### ISSUE THREAD

**Issue by hammerandtongs** [nushell/reedline#100]
https://github.com/ardagnir/athame

Given the high cost of implementing good vi bindings perhaps this is a good approach.

**Comment by sholderbach** [comment]
Definitely great to have the option to hook into a true vim/nvim engine. But for the library to be generally used, having to externally depend on either neovim or the more recent Vim 8.0 severely limits the portability. So this would probably be more a future opt-in alternative to support even more of full vim. In the meantime we probably better implement the core functionality for the 80% experience with 20% effort.

**Comment by morzel85** [comment]
In case of very complex edits one should just launch real Vim (`Ctrl+o` in Reedline, `v` in Readline)...
