### ISSUE TITLE
[Bug] crossterm error mapping alt on Mac + enter doesn't accept modifiers

### ISSUE THREAD

**Issue by mzanrosso** [nushell/reedline#109]
crossterm doesn't map the "command" key on Mac so we cannot use for example the multiline editor

**Comment by fdncred** [comment]
I thought it worked like this for key translations between mac and windows. Command=Control, Option=Alt, Shift=Shift. Also, the rustyline maintainer has pointed us to [this ](https://superuser.com/questions/357355/how-can-i-get-controlleft-arrow-to-go-back-one-word-in-iterm2/357394#357394)in the past.

**Comment by jntrnr** [comment]
Yeah, this should work. @mzanrosso are you seeing issues on the Mac where a keybinding isn't working?

**Comment by mzanrosso** [comment]
@jntrnr - I'm testing the crossterm crate and it seems that when I hit enter it will not pass any modifiers even with the basic shift + option on Mac is not recognized by crossterm so I'm not able to use some of the actual keybindings

**Comment by jntrnr** [comment]
Which keybinding did you try? Some of them aren't supported in Mac because of Mac's design, but others should work.

**Comment by mzanrosso** [comment]
@jntrnr - all the keybindings  with `KeyModifiers::ALT` is not working on a Mac right now

**Comment by fdncred** [comment]
I've tested and while command is not supported by crossterm, key modifiers with alt, shift, control work on Mac. If we wanted to add command or even the windows key, it would probably have to be upstream in the crossterm crate. With that in mind, I think we should probably close this issue. Please reopen if you disagree.
