### ISSUE TITLE
Move the clear screen/`Ctrl-L` logic inside the line editor engine

### ISSUE THREAD

**Issue by sholderbach** [nushell/reedline#120]
We currently handle the `Ctrl-L` screen clearing command by exiting the `read_line()` method with the `Signal::CtrlL` and keeping the line buffer state as is. This requires the `read_line()` method to respect the previous state of `Reedline` and collaboration from the side of the consumer. 
This might be less than optimal. We might consider moving the `Ctrl-L` handling into the `Reedline` engine with a call to the painter and maybe provide the Option to disable this. A public method to clear from the side of the consumer is already existing.

**Comment by stormasm** [comment]
https://github.com/jntrnr/reedline/issues/132

I noted some strange behavior with Ctrl-L in the above issue...

**Comment by stormasm** [comment]
Unfortunately, this did not fix it...
I am seeing the same exact issue on my Macbook as before...

When you hit command K it clears the screen buffer, but on the next
key stroke it takes you back to the bottom of the screen which you don't
want.

When you hit Ctrl - L it does not clear the screen buffer....

The famous @fdncred ansi command still works like a charm 👍

**Comment by stormasm** [comment]
For reference here is my version of the @fdncred command

```rust
alias cls = $"(ansi cls)(ansi clsb)(ansi reset)(ansi home)"
```

**Comment by fdncred** [comment]
@stormasm I think if you look at the `keybindings default | find clear` you'll see that `ctrl+l` is mapped to `ClearScreen` but there is a new command called `ClearScrollback`. So, I'm speculating here that you may need to define a new keybinding to do both clearscreen and clearscrollback.

Or maybe just clearscrollback - this is what it does but i'd have to lookup those cleartypes to understand exactly what it's doing.
```rust
    pub(crate) fn clear_scrollback(&mut self) -> Result<()> {
        self.stdout
            .queue(crossterm::terminal::Clear(ClearType::Purge))?
            .queue(crossterm::terminal::Clear(ClearType::All))?
            .queue(cursor::MoveTo(0, 0))?
            .flush()?;
        self.initialize_prompt_position()
```

**Comment by fdncred** [comment]
I just added this keybinding to nushell and it works to clear the screen and clear the scrollback, *BUT* you have to hit it twice. This test was in windows.
```
    {
        name: clear_everything
        modifier: control
        keycode: char_l
        mode: emacs
        event: { send: clearscrollback }
    }
```

**Comment by stormasm** [comment]
So here is my (strong) opinion on this matter (and I am speaking for all of our Macbook users who use this terminal)...

We should have a way to solve this problem out of the box for our users.
They should not have to do anything....

Currently the @fdncred solution works for me with my alias...
It is a fine solution / but its not part of nushell...

Ideally some keystroke should be builtin to nushell for all the
other users who don't have this alias defined...

Or just bake this alias into the default script / or some keystroke
into nushell that is well known and documented.

Preferably CMD-k or Ctrl-L

Until it works that way IMHO its not fixed... 👍

**Comment by fdncred** [comment]
so, if i understand you right @stormasm, you want to clear the screen and clear the scrollback buffer all at once, correct? is that the normal thing on linux and mac with the `clear` command?  it seems to work that way with nushell's `clear` command.

**Comment by stormasm** [comment]
Ideally I would like it to work the exact same way as the @fdncred command / alias works which I think is to do both ?

**Comment by fdncred** [comment]
> Ideally I would like it to work the exact same way as the @fdncred command / alias works which I think is to do both ?

but if this is just a preference, i'm not sure we should do it. if it's a standard, we definitely should do it. that's what i'm trying to get at.

**Comment by stormasm** [comment]
Cmd-K does both...

**Comment by fdncred** [comment]
it's interesting that Apple's documentation for terminal keybindings is a little vague, imo. I wouldn't guess that cmd-k and cmd-l work the way you say after looking at the docs.

|description|shortcut|
|-|-|
|Clear to start | Command-K|
|Clear to previous mark | Command-L|


https://support.apple.com/en-asia/guide/terminal/trmlshtcts/2.12/mac/11.0

**Comment by stormasm** [comment]
```rust
Clear to start       Command-K
```

I am assuming that "Clear to start" means "clear the screen buffer"

**Comment by fdncred** [comment]
agreed, now that we've tested that and can see evidence of that, but the documentation doesn't spell that out.

**Comment by stormasm** [comment]
in general the apple / mac documentation "has lots of room for improvement" 😄

**Comment by sholderbach** [comment]
To solve this there are three separate issues:

- `Command-K` and **Command**`-L` (If I understand correctly it uses those special marks similar to kitty) are special sauce in Macs terminal. Here the terminal emulator takes care of clearing but we are not able to detect the keypress. If the line editor is basically just working with the Save and Restore cursor position commands of VTwhatever ANSI this is not much of an issue . If you basically only restore the cursor. For the fancier display we want to be able to *know* in absolute terms where we are on the screen for the menu stuff etc. Thus we keep the cursor position stored (polling it is expensive) and lacking some kind of event the result is a borked screen where the prompt is where it was before pressing `Command-k`. Solution to this is probably hidden somewhere in how zsh/fish get everything to work on the mac after pressing `Command-k`
- Doing the proper clear for the scrollback buffer. On Linux (gnome-terminal, kitty, alacritty, vscode terminal) I was able to resolve that by reordering the current screen clear before the scrollback purge (using the same crossterm commands) (basically @stormasm 's version of the nushell command sequence minus the *style* reset)
> For reference here is my version of the @fdncred command
> 
> ```rust
> alias cls = $"(ansi cls)(ansi clsb)(ansi reset)(ansi home)"
> ```

- In @fdncred 's full terminal reset command https://github.com/nushell/nushell/issues/5089#issuecomment-1087932140 there are additional features that are hard to get absolutely crossplatform. The extra reset `ESC c` (https://en.wikipedia.org/wiki/ANSI_escape_code#Fs_Escape_sequences) is probably not really defined for older Windows terminals? At least it is currently not covered by crossterm

**Comment by fdncred** [comment]
this works for me with the latest reedline changes (not in nushell yet).
```
    {
        name: clear_backbuffer
        modifier: control
        keycode: char_l
        mode: emacs
        event: { send: ClearScrollback }
    }
```

**Comment by stormasm** [comment]
Its working !!  Yeh !!
I am closing this issue...
https://github.com/nushell/nushell/pull/5405
