### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by jntrnr** [nushell/reedline#135]
failures:

---- src/lib.rs - (line 120) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/lib.rs:31:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- src/lib.rs - (line 34) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/lib.rs:26:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- src/lib.rs - (line 98) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/lib.rs:21:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- src/lib.rs - (line 79) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/lib.rs:18:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    src/lib.rs - (line 120)
    src/lib.rs - (line 34)
    src/lib.rs - (line 79)
    src/lib.rs - (line 98)

test result: FAILED. 15 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.84s

error: test failed, to rerun pass '--doc'
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101

**Comment by jntrnr** [comment]
I'm going to close this one as I haven't seen it lately. We can reopen if it recurs

**Comment by sholderbach** [comment]
This seems to be caused by the default constructor for `Reedline` creating a history with file access which probably fails in the ci with this rather weird message. I stumbled accross this again when fixing another doccomment and forgetting to set the `no_run` marker
