### ISSUE TITLE
Some characters that use modifiers are not printed

### ISSUE THREAD

**Issue by elferherrera** [nushell/reedline#136]
Using a spanish keyboard layout, in order to access to the chars `[  ]` or `{  }` one needs to use the modifier `alt gr`. Reedline does not print those characters when using this layout. If I change it to an english layout, the characters can be printed (they dont need the `alt gr` key).

This is the output from `cargo run -- -k`
![image](https://user-images.githubusercontent.com/6942205/131246687-a359736b-1aa8-4abe-afea-5e4c3cf702eb.png)

It seems that the events are captured, but reedline doesnt print the characters

**Comment by sholderbach** [comment]
With your fix in #139 this seems to be resolved. I was able to enter `AltGr` characters with a German keyboard layout in two terminal emulators (gnome-terminal, vscode)
