### ISSUE TITLE
Visibility issue with HistoryAppender and HistoryView

### ISSUE THREAD

**Issue by gwenn** [nushell/reedline#158]
See https://docs.rs/reedline/0.2.0/reedline/trait.History.html
And https://github.com/nushell/reedline/blob/main/src/lib.rs#L202
I am not sure. Maybe you don't want users to provide their own implementation.

**Comment by sholderbach** [comment]
The split into `HistoryAppender` and `HistoryView` reflects more the discussion leading to the current implementation than the actual practical implementation at the moment.

In my view the crate should supply the reasonable implementations for history (with future options regarding file format/database for persisting). At the moment with the `HistoryNavigationQuery` we subtly expose a bit more internals than maybe reasonable to make public. 
But if there are reasonable use cases for user defined History implementations we can certainly try to change that.
Let us know your thoughts, as a rustyline expert you probably have valuable experience on that.

**Comment by gwenn** [comment]
See https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cbad985782c795a91a3196ef1fd4d84c
=> I can't provide my own implementation.

**Comment by gwenn** [comment]
Thanks.
