### ISSUE TITLE
hints disappearing - weird completions

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#218]
kind of hard to describe so here is a mov.

https://user-images.githubusercontent.com/343840/147612767-6671cb76-e469-44e5-8bc4-d29c0d386387.mov

**Comment by sholderbach** [comment]
Display issues should be out of date with #217, but I will leave it open as I had similar weird behavior with navigation through content related to history and hint completions but can not narrow it down for now

**Comment by fdncred** [comment]
I've started to have different issues on the latest main. if I have a fairly long command that wraps in engine-q when I hit left or right arrow the prompt is duplicated up the screen.

<img width="1151" alt="Screen Shot 2021-12-30 at 9 55 01 PM" src="https://user-images.githubusercontent.com/343840/147802384-63710b93-aad6-400e-9ba1-d50ebdb1f586.png">

long command `$"(ansi -e { fg: '#000000' bg: '#f74c00'})(char -u e7a8) ((rustc --version | decode utf-8 | split column ' ' | get Column2).0) (ansi reset)"`

**Comment by sholderbach** [comment]
Seems to be outdated with several painter fixes
