### ISSUE TITLE
Potential history corruption through different processes/`FileBackedHistory` instances

### ISSUE THREAD

**Issue by sholderbach** [nushell/reedline#221]
As soon as the `FileBackedHistory` reaches it capacity, writes are not performed via appending, instead the history loaded into memory at the initialisation of the `FileBackedHistory` will be written with the new entries of the particular instance. If two processes or instances are alive at the same time the last one to `drop` will overwrite the previous additions.

https://github.com/nushell/reedline/blob/b242a030aac7f0176fce0e68c89c8ad6a3655ba1/src/history/file_backed.rs#L246-L254

**Comment by fdncred** [comment]
seems like a shared `rolling log` type infrastructure would help. either that or have someone finish my db-backed-history - LOL.

**Comment by sholderbach** [comment]
That's a great suggestion if we want to keep a human greppable file! But yeah I was fantasizing about the ability to rank the history hints by usage frequency, so we may want to go the same route as IPython with sqlite

**Comment by fdncred** [comment]
We'll definitely (eventually) have a sqlite backed history. I'm just not sure when. there are lots of things I want to do with it.

**Comment by elferherrera** [comment]
Could it be trait so that we can ship with a file or a db?

**Comment by sholderbach** [comment]
History is already a trait object. but the current setup would lead to some duplication when it comes down to navigation.
