### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by jntrnr** [nushell/reedline#256]
It's been a while since we did a release of reedline to crates.io. Is it time to do a new one?

**Comment by elferherrera** [comment]
I think once e-q is merged we should set up a fixed release period for it

**Comment by fdncred** [comment]
it seems like we hit a milestone with @elferherrera's contextmenu implementation. I vote to publish.

**Comment by sholderbach** [comment]
Any bugs found in e-q use, that classify as high priority (breaking the experience significantly)? I think we should check if the open issues might be closed since the painter fix by @elferherrera
