### ISSUE TITLE
Last line of command is overwritten in mulit-iline when cursor is not in last line

### ISSUE THREAD

**Issue by x3rAx** [nushell/reedline#261]
I noticed, that the last line of a multi-line `do { ... }` command is overwritten by the output:

Take this example:

```
do {
echo '########'
echo 'this is'
echo multi-line }
```

If you position the cursor in the last line `echo multi-line }` and hit enter, the output is printed to the next line, as it should.

If you however place the cursor in any of the other lines (e.g. `echo 'this is'`) then the first line of the output overwrites the last line of the command:

```
do {
::: echo '########'
::: echo 'this is'
######## multi-line }
this is
multi-line
```

Notice the line `######## multi-line }` where `########` overwrote the `::: echo` of the command.

I tested this using the following builds:

- `cargo run --features extra --release`
- `cargo run --features extra`
- `cargo run`
- `cargo run --release`

**Comment by fdncred** [comment]
i thought this was more of a reedline issue so i transfered it here. let me know if i'm mistaken.

**Comment by x3rAx** [comment]
Well, I guess it is but I don't know :sweat_smile: 

Thanks!

**Comment by sholderbach** [comment]
Can reproduce with reedline standalone.

**Comment by fdncred** [comment]
I ran into this today in e-q. notice how the command should wrap around but the output is stomping on it.
![image](https://user-images.githubusercontent.com/343840/150824314-e8b2f6bb-b8cb-44e1-997b-4ac15b1dc7d6.png)

**Comment by x3rAx** [comment]
Thank you @sholderbach , I updated dependencies of engine-q locally so reedline is the latest version and it's now working :smiley_cat:
