### ISSUE TITLE
token by token completion going left/backward

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#272]
**Platform** Mac
**Terminal software** kitty

Describe the problem you are observing.

## Steps to reproduce
1. type a command that has multiple tokens in a hint
2. type option-right-arrow to complete tokens
3. type option-left-arrow to remove completed tokens and turn them back into hints <-- this doesn't work.

## Screenshots/Screencaptures

![token-complete](https://user-images.githubusercontent.com/343840/150614502-7036a4cf-dcea-4162-bd59-e277c010c45a.gif)

**Comment by fdncred** [comment]
I guess it's me because option-delete works like I want option-left-arrow to work. I'm just not sure how to create that keybinding.

**Comment by sholderbach** [comment]
Does not seem to be an explicit feature in either fish or zsh:
https://fishshell.com/docs/current/interactive.html?highlight=autosuggestion#autosuggestions
https://github.com/zsh-users/zsh-autosuggestions

Can be emulated with the `BackspaceWord` edit command but might have slightly different word definitions in the future.

Having an explicit `PartialHintUndo` or else command would require keeping and updating additional state.

**Comment by fdncred** [comment]
Thanks for helping. I think I'll close this but leave this information too, since I was on a Mac when trying to make this work.
```
 # mac keyboard
 home = fn + left
 end = fn + right
 pageup = fn + up
 pagedown = fn + down
 backspace = delete
 delete = fn + delete
```

so, if someone wanted to emulate the rust code keybinding of `kb.add_binding(KM::ALT, KC::Delete, edit_bind(EC::DeleteWord));` on a Mac, you'd have to press <kbd>fn</kbd> + <kbd>option</kbd> + <kbd>delete</kbd> on your keyboard, which isn't super intuitive, and this would delete the word to the right of the cursor.
