### ISSUE TITLE
pasting data with leading spaces

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#274]
**Platform** Windows
**Terminal software** Windows Terminal

Describe the problem you are observing.

## Steps to reproduce
1. if you copy and past "     ls" in engine-q, it will run the command but the output is shifted.
2. another example is if you copy and past this "        let weather_runtime_file = (($env.TMP) | path join weather_runtime_file.json)
" you won't be able to see the line in engine-q. The paste seems to work, and it's in your history, but you don't see the command on the screen at all.

## Screenshots/Screencaptures

paste with WT warning message
![image](https://user-images.githubusercontent.com/343840/150827800-c93a4965-6e8c-4e1a-bf9a-ffee18867826.png)

after you click paste anyway - i expect to see the command in the terminal
![image](https://user-images.githubusercontent.com/343840/150828105-9dbd67d2-4a25-4500-b6f9-901a8d7cd4bd.png)

the entries in the history
![image](https://user-images.githubusercontent.com/343840/150827695-a9be4a64-b023-4be0-b747-92056ff3dc2a.png)

perhaps strings should be trimmed when pasting?

**Comment by sholderbach** [comment]
The problem around not showing it should be solved by the fix for #282, I think trimming is probably something that would be dependent on the use case. I could imagine it being useful to have a formatter for the history or even the prompt line but having a trim by default is probably making assumptions.

**Comment by fdncred** [comment]
seems to work in reedline. need to get it in e-q to play a bit more but closing this anyway.
