### ISSUE TITLE
Issues with pasting.

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#282]
**Platform** Windows 10
**Terminal software** Windows Terminal

Describe the problem you are observing.

When pasting multi-line statements in engine-q, not all of the statements get pasted. We can move this to e-q if it's not a reedline issue.

## Steps to reproduce
1. paste this
```
let-env current_page = 0
alias pp = (let cmds = (help commands | range ($env.current_page - 10)..($env.current_page)); let-env current_page = ($env.current_page - 10); echo $cmds)
alias hh = (let cmds = (help commands | range ($env.current_page)..($env.current_page + 10));  echo $cmds)
alias nn = (let cmds = (help commands | range $env.current_page..($env.current_page + 10)); let-env current_page = ($env.current_page + 10); echo $cmds)
```
2. I ran `$scope.aliases` and only had the `hh` alias. I also didn't see all of the text pasted in the terminal. I only saw the `alias nn ...` line
3. separate, but maybe related, i've also see odd behaviors when pasting text with leading spaces.
4. the only way i could get it to work was to copy-n-paste each line individually.

**Comment by elferherrera** [comment]
This one is tricky because you are not pasting a multi line command but multiple commands
