### ISSUE TITLE
duplicate entries in completion menu

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#300]
**Platform** e.g. macOS
**Terminal software** Tabby

Describe the problem you are observing.

## Steps to reproduce
1. type key<tab>
2. see duplicates
3. A side note here - I also cannot arrow down to get to the other menu items.

## Screenshots/Screencaptures

![dupes](https://user-images.githubusercontent.com/343840/152663250-e294d12e-2ab1-440f-a178-b8fdb74555b5.gif)

/cc @elferherrera

**Comment by elferherrera** [comment]
I think the completer is repeating those entries

**Comment by elferherrera** [comment]
I think it does come from the completer. If you add a space after keybindings it gets you the unique values

![Animation3](https://user-images.githubusercontent.com/6942205/152685514-3cbe17a8-29fd-48dc-a176-b5a5dbcdb405.gif)

**Comment by fdncred** [comment]
agreed. I see the same thing.  how do we not show duplicates?

**Comment by jntrnr** [comment]
imho, the duplicates and sorting should be handled by the thing making the completions list (the implementer of that trait)

**Comment by jntrnr** [comment]
Might have a fix for this. Looking now

**Comment by jntrnr** [comment]
Found it. PR incoming

**Comment by fdncred** [comment]
nice!
