### ISSUE TITLE
history menu won't appear until I hit backspacehistory.

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#301]
**Platform** e.g. macOS
**Terminal software** Tabby 

I hit ctrl-x to make the history menu appear. you can see my marker as `H> ` but no history will appear until I hit backspace.

## Steps to reproduce
1. hit ctrl-x to try to make the history menu appear
2. observer lack of history menu
3. hit backspace and history menu appears
4. note - ctrl-z is previous_history_menu and ctrl-x is next_history_menu on my Mac

## Screenshots/Screencaptures
![history](https://user-images.githubusercontent.com/343840/152663351-0c2e2af9-a666-4854-bfb8-a82502ac2902.gif)

**Comment by fdncred** [comment]
still not working for me.

**Comment by sholderbach** [comment]
This seems to be fixed now
