### ISSUE TITLE
Does reedline publish new version into crate.io?

### ISSUE THREAD

**Issue by baoyachi** [nushell/reedline#313]
I see `nushell` use reedline dependencies with github link. Now I want use this features [Make up/down be one-press-per-history ](https://github.com/nushell/reedline/commit/8c565e4f1de2c6dd4f67b18876d011756bfbe16d).

**Comment by fdncred** [comment]
There is a reedline [published](https://crates.io/crates/reedline) but it's not up to date with the main branch. I'm pretty sure that we plan to publish reedline in conjunction nushell's next release.

**Comment by baoyachi** [comment]
That's great.I'm looking forward to it. I really need the new version of reedline on crates.io
