### ISSUE TITLE
Cannot change the color in a custom prompt

### ISSUE THREAD

**Issue by kyp44** [nushell/reedline#314]
**Platform** Ubuntu 20.04.3
**Terminal software** gnome-terminal
**Rust version** rustc 1.60.0-nightly (75d9a0ae2 2022-02-16)

## Steps to reproduce
1. Create a struct and implement the `Prompt` trait on it
2. Try to override the `get_prompt_color` method to return a different color

## Problem
The problem is that I cannot override `get_prompt_color`. If I have it return `crossterm::style::Color` the compiler gives an error saying that the implementation does not match the trait and that a return type of `crossterm::style::types::color::Color` is expected.

If I change the return type to `crossterm::style::types::color::Color` to fix this, I get an error because `crossterm::style::types::color` is a private module.

Not sure if this is a genuine problem or I am doing something wrong. Also it may be that something changed in `crossterm` to cause this.

**Comment by sholderbach** [comment]
This was most likely a result of different crate versions specified in your `Cargo.toml` vs reedlines specified version. I observed similar less than ideal error messages when having a version incompatibility regarding crossterm.

**Comment by sholderbach** [comment]
Closing this as this should not be an issue with expllicit versions on crates.io and we try to stay up to date on `crossterm`
