### ISSUE TITLE
Is reedline full-duplex? How do I `print_line` while `read_line`ing?

### ISSUE THREAD

**Issue by vi** [nushell/reedline#320]
Is a chat-like application an intended use case for Reedline? If no, it should be explicitly documented. If yes, a sample that prints messages from a timer while simultaneously allowing user to edit the command line should be provided.

I don't see this feature in neither of Rust readline crates, it is even absent from a comparison table. It is also absent from [Brainstorming Features](https://github.com/nushell/reedline/issues/63) issue - is it only for user-facing features or also for system ones like support for async or custom file descriptors?

**Comment by fdncred** [comment]
I'm not sure we've ever considered this use case. It's interesting.

**Comment by sholderbach** [comment]
This idea is similar to #236. There is certainly some interest to be able to have some background process/thread/task printing without disrupting the layout of the prompt.
Currently we certainly focus first and foremost to achieve a stable version for use in nushell. But we should come back to that in the future.

**Comment by GrxE** [comment]
Hi all! 
Due to my need for an external printer,I made a very basic ExternalPrinter as an optional feature. You can take a look: https://github.com/GrxE/reedline. 
Do you want me to make a PR?

**Comment by sholderbach** [comment]
Awesome @GrxE,  we would be happy to take a look!

**Comment by sholderbach** [comment]
MVP landed in #467.
