### ISSUE TITLE
`can_partially_complete` panics on matches that differ by uppercase/lowercase

### ISSUE THREAD

**Issue by jntrnr** [nushell/reedline#339]
**Platform** macOS
**Terminal software** iTerm2

Describe the problem you are observing.

## Steps to reproduce
1. open Nushell
2. type `open ./C<tab>`

My guess is that because there's both a capital-C ./Cargo.toml and a lowercase-c "./crates" that the `can_partially_complete` panics because there isn't a common prefix? This is just a guess though.

related: https://github.com/nushell/nushell/issues/4751

**Comment by sholderbach** [comment]
Seems to be fixed now
