### ISSUE TITLE
Transient prompt support

### ISSUE THREAD

**Issue by jmoore34** [nushell/reedline#348]
Possible alternative to #195 

Powerline prompts can be nice, but they can also fill the scrollback history with a lot of visual noise. Some readline implementations support transient prompts, in which after the user hits 'enter', the fancy powerline prompt is replaced with a much simpler prompt. 

Here is an example with zsh's powerlevel10k:
![transient 2](https://user-images.githubusercontent.com/1783464/158272359-15571bf6-ccec-4f38-aa56-84adfea438bf.gif)

**Comment by sholderbach** [comment]
This definitively needs additional support from reedlines side to paint a different prompt after submission of an entry. Good catch!

**Comment by Cactus-man** [comment]
I feel like before this is done the prompting system in general should be reevaluated before, as behavior in some possible situations is not well-defined. Most importantly, how should a prompt behave on line break characters in certain parts? In its current state it behaves unexpectedly (though I'd argue there's no "expected" behavior in this case anyway).  

![image](https://user-images.githubusercontent.com/64769435/211161766-bd9032d0-f03f-49be-8d79-bc8225dad80e.png)
_Fig 1. `Prompt::render_prompt_left` returns a string with line break_

![image](https://user-images.githubusercontent.com/64769435/211161808-94a4f41a-7cfd-4a3a-af81-29266c953489.png)
_Fig 2. the same as Fig 1. but in a different terminal_

This might seem obvious to not do if encountered by a developer but it reflects an asymmetry within the prompt rendering code which currently inhibits arbitrary Unicode prompts, which could be right-to-left.

**Comment by fdncred** [comment]
transient prompt was implemented a while back, thanks.
