### ISSUE TITLE
zellij incompatibility

### ISSUE THREAD

**Issue by N4tus** [nushell/reedline#359]
### Describe the bug

I'm not sure if this is the right place to post this error, since it involves running nu inside of zellij.

Running nu inside of zellij causes the prompt to override the output of the command, if the plane full.

### How to reproduce

- install both zellij and nu
- run zellij
- run nu
- enter some command until the pane is full
- enter command and observe that the prompt overrides the output

### Expected behavior

running inside of zellij should behave the same as outide.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.0                                      |
| branch             | main                                        |
| short_commit       | 22528339                                    |
| commit_hash        | 225283391779978ae3a2bdfe0dd4fb2af8e9bd0c    |
| commit_date        | 2022-03-25 17:00:35 +00:00                  |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (5f4e06771 2022-03-10) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (65c8266 2022-03-09)   |
| pkg_version        | 0.60.0                                      |
| build_time         | 2022-03-25 18:37:10 +01:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  |                                             |

**Comment by sholderbach** [comment]
OK first debugging round shows that zellij seems to differ from a normal terminal emulator and tmux in not executing a scroll up command that is used with the logic to finalize a line found here https://github.com/nushell/reedline/blob/2e0d35187c5433001a8a0c8d31f062c83cbd482e/src/painting/painter.rs#L411-L425

![image](https://user-images.githubusercontent.com/15833959/160205186-a25ea25c-3864-49ff-92d3-40fb9836ab79.png)

**Comment by imsnif** [comment]
Hi, I'm one of the Zellij maintainers. This is our bug - thanks for debugging this. Minimal reproduction:

`echo -e "line1\033[Sline2`

Without Zellij:
```
line1
     line2
```

With Zellij:
```
line1line2
```

Will issue a fix for this on Monday and we're releasing a version shortly after anyway. Apologies for the inconvenience!

**Comment by sholderbach** [comment]
Awesome, thanks for the quick response @imsnif.
Will close the issue on our side, feel free to reopen if there are problems/incompatibilities with that approach, then we can probably figure out an alternative way using cursor movements and newlines

**Comment by imsnif** [comment]
FYI: this is fixed in Zellij `0.27.0`

**Comment by sholderbach** [comment]
Awesome, thanks!
