### ISSUE TITLE
CutWordLeft cutting to much?

### ISSUE THREAD

**Issue by chtenb** [nushell/reedline#377]
### Describe the bug

When I press ctrl-w in emacs mode it often happens that nushell will remove more than my intended cut

### How to reproduce

1. Type `asdf -- `
2. Press Ctrl-W
3. Find that everything got deleted 

### Expected behavior

Only delete backwards until the next whitespace separator

**Comment by sholderbach** [comment]
Same issue as in #346. Also affects the moves. There are some questions about the word definition we should resolve i.e. `echo (test)` (Parantheses or quotation), `snake_case`, `$test.member`. Different editors have their quirks there.
