### ISSUE TITLE
Arrow keys stop working after running dotnet or ssh

### ISSUE THREAD

**Issue by rgwood** [nushell/reedline#407]
**Platform** Linux x86 (Fedora 36)
**Terminal software** GNOME Terminal

Hello from `nushell/nushell`! I've been looking into [this Nu issue](https://github.com/nushell/nushell/issues/5220), and I've put together a minimal reproduction for Reedline v0.4.0. Here's a dumb little REPL that runs whatever command it's given:

```rust
use reedline::{DefaultPrompt, Reedline, Signal};
use std::{io, thread, time};

fn main() -> io::Result<()> {
    let mut line_editor = Reedline::create();
    let prompt = DefaultPrompt::default();

    loop {
        let sig = line_editor.read_line(&prompt)?;
        match sig {
            Signal::Success(buffer) => {
                println!("We received: {buffer}");
                let mut process = std::process::Command::new("sh");
                process.arg("-c").arg(&buffer);
                process.spawn().expect("process spawn error");

                // avoid writing prompt while external process is still running
                thread::sleep(time::Duration::from_millis(100));
            }
            _ => {
                println!("Abort!");
                break Ok(());
            }
        }
    }
}

```

## Steps to reproduce
1. `cargo run`
2. Type "ls" then `enter` to run ls
3. Press up arrow then down arrow, observe that the history navigation works as expected :+1: 
4. Type "dotnet --version" then `enter` (requires [the .NET SDK](https://dotnet.microsoft.com/en-us/download/dotnet))
5. Press the up arrow, observe that nothing happens :-1: 

I was also able to reproduce the issue with SSH in Nu, but that's proving to be a little trickier in my minimal repro.

## Next Steps

I'd be happy to investigate further, but I think I've reached the limit of my terminal debugging knowledge. If someone can point me in the right direction that would be much appreciated.

 [@elferherrera suggested that this might be a crossterm issue](https://github.com/nushell/nushell/issues/5220#issuecomment-1101451322); I guess I could try building a similar REPL directly with crossterm but I'm hoping someone will have an easier idea.

**Comment by rgwood** [comment]
Using `script`like `script -q -c 'dotnet --version' output.txt` I was able to see the raw command output and investigate this further. It seems like Reedline doesn't like certain escape characters that `dotnet` outputs. 

I can reproduce this by calling `cat` on either of these files in Nu: [dotnet-version-raw-output.txt](https://github.com/nushell/reedline/files/8542808/dotnet-version-raw-output.txt), [minimal-repro.txt](https://github.com/nushell/reedline/files/8542809/minimal-repro.txt)

![image](https://user-images.githubusercontent.com/26268125/164765008-96b49096-0aec-4e32-90db-f1cdb5f69619.png)

It seems like that `[?1h]` control code sets a special "application mode" for arrow keys: https://www.vt100.net/docs/vt510-rm/DECCKM.html

So... I think the `dotnet` CLI is behaving badly here (related issues: [1](https://github.com/dotnet/runtime/issues/27626), [2](https://github.com/dotnet/sdk/issues/15243) ), but I _don't_ understand why other shells handle it OK. And given that this happens with `ssh` too, I suspect this may still need a fix on Reedline or Crossterm's side :(

**Comment by fdncred** [comment]
just to document a work-around `ansi -e ?1l` corrects the issue as does `$"(ansi esc)c"` or `"\ec"` but the last 2 also clear the screen.

**Comment by rgwood** [comment]
Closing this; @fdncred was able to fix it in https://github.com/nushell/nushell/pull/5302 (thank you!).

To make a long story short, Nu can now tell the terminal to reset cursor key mode before each prompt. We think this is how other shells solve the problem.
