### ISSUE TITLE
Keybinding to enter a newline

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/reedline#426]
It would be great if there was a way to insert a newline without executing the current text. On zsh/Python, the shortcut for this is `Ctrl+V Ctrl+J`.

**Comment by jmoore34** [comment]
I think it exists - the `InsertNewline` event

**Comment by jmoore34** [comment]
For instance, in nushell, you could enable it like so:

config.nu
```
let-env config = {
...
    keybindings: [
    ...
    {
        name: newline
        modifier: shift
        keycode: Enter
        mode: emacs
        event: [
            { edit: InsertNewline }
        ]
    }

**Comment by ajeetdsouza** [comment]
I've tried this, but on my system (macOS 12.3.1 + stock Terminal) it doesn't do anything.

**Comment by jmoore34** [comment]
Does it work with a different keybinding? Also, could you post the output of `version`?

**Comment by ajeetdsouza** [comment]
I've tried `modifier=CONTROL; keycode=Esc` but that didn't do anything either.
```
╭────────────────────┬─────────────────────────────────────╮
│ version            │ 0.62.0                              │
│ branch             │                                     │
│ tag                │                                     │
│ build_os           │ macos-aarch64                       │
│ build_os           │ aarch64-apple-darwin                │
│ rust_version       │ rustc 1.60.0 (7737e0b5c 2022-04-04) │
│ rust_channel       │ stable-aarch64-apple-darwin         │
│ cargo_version      │ cargo 1.60.0 (d1fd9fe2c 2022-03-01) │
│ pkg_version        │ 0.62.0                              │
│ build_time         │ 2022-05-16 11:53:49 +05:30          │
│ build_rust_channel │ release                             │
│ features           │ default, trash, which, zip          │
│ installed_plugins  │                                     │
╰────────────────────┴─────────────────────────────────────╯
```

**Comment by jmoore34** [comment]
Perhaps try with a non-special key, e.g. ctrl+n

**Comment by jmoore34** [comment]
You can also do `keybindings listen` to test which keybindings your terminal can pick up

**Comment by ajeetdsouza** [comment]
I tried `Ctrl+Enter`, `Option+Enter`, `Shift+Enter`, and `Command+Enter`. None of these modifiers seem to be picked up:

```
code: Enter, modifier: NONE, flags: 0b000000
```

It turns out that the bug is that `mod+Enter` is not being detected correctly. When I change the keybinding to `CONTROL` and `char_j`, it works.

**Comment by jmoore34** [comment]
If I had to guess, I imagine it would be a limitation of the terminal emulator. Ctrl+enter and shift+enter both work for me w/ Windows Terminal.

**Comment by sholderbach** [comment]
According to https://github.com/nushell/reedline/pull/399#issuecomment-1103833544 `Shift-Option-Enter` seems to be mapped to a modfied enter.
We currently do not support general chord style keybindings, only the hardcoded vi emulation understands key sequences.

**Comment by ajeetdsouza** [comment]
I just tried `fish_key_reader` on the `fish` shell, and it wasn't able to detect any modifiers either. I suppose it's macOS problem, then. Thanks for all the help!
