### ISSUE TITLE
Export `crossterm::event::{KeyCode, KeyModifiers}` from Reedline

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/reedline#456]
Given that the `add_binding` function in `reedline` requires an input of `KeyCode` and `KeyModifier`, I think we should export these enums. Otherwise, one has to not only add `crossterm` to their Cargo.toml, but also ensure that the version number exactly matches the one used by reedline.

**Comment by fdncred** [comment]
crossterm also has a new "kind" KeyEventKind in v0.24. I'm not sure if/how we should use it and it may need to be lumped in with this request.
```
 pub const fn new_with_kind(
         code: KeyCode,
         modifiers: KeyModifiers,
         kind: KeyEventKind,
     ) -> KeyEvent {
         KeyEvent {
             code,
             modifiers,
             kind,
         }
     }
```

**Comment by sholderbach** [comment]
Didn't know about this strategy, was unsure about the linking rules in that case.

But that seems to be at least a recommended practice: 
https://www.lurklurk.org/effective-rust/re-export.html

As crossterm has to do some global stuff to read events and changes some semntics often as a pre `1.0`, I think trying to use the compatible crossterm version is sstill recommended, but should be not an issue for those dumb enums/types.
