### ISSUE TITLE
Consecutive dot expansion similar to pufferfish plugin

### ISSUE THREAD

**Issue by zim0369** [nushell/reedline#465]
There's a plugin for fish: https://github.com/nickeb96/puffer-fish
which expands consecutive dots to extra double dots making it easier to go to previous dirs. 

I don't think this feature would disrupt any other commands.

**Comment by sholderbach** [comment]
While not with the exact behavior of expanding in the line directly this is implemented in the existing nushell completer in the style of how `zsh` does it (take `...` and internally expand it to `../../`). Also I don't think it would need a particular reedline change to support your behavior on the nushell side. Reopen if the API could be improved.
