### ISSUE TITLE
Shift-enter to insert a line break inside a command without running

### ISSUE THREAD

**Issue by webbedspace** [nushell/reedline#491]
It'd be nice to press shift-enter to insert a line break inside a command (such as when you type `def foo [] {}` and decide to insert a line break between `{}` without running the command.

## References

This feature exists in most browser consoles (see: Firefox, Chrome) as well as various IRC-like places (like Twitter DMs or Slack).

**Comment by fdncred** [comment]
Add something similar to this in your keybindings.
```
    {
        name: insert_newline
        modifier: alt
        keycode: enter
        mode: emacs
        event: { edit: insertnewline }
    }
```

**Comment by webbedspace** [comment]
Thanks.
