### ISSUE TITLE
Make insertion to the history optional (e.g. with leading space)

### ISSUE THREAD

**Issue by sholderbach** [nushell/reedline#516]
Currently all submitted entries are directly appended to the history. (With the sqlite history we support amending the history entry afterwards based on an ID that is not part of the text based history)
This might not always be desired (e.g. dangerous operation, something containing a secret key/password).
Some shells support ignoring all lines that start with a space.

Goal: allow us to make history insertion conditional/optional

Requirements: 
- Needs to also work with the simple text based history.
- hardcoding space at the beginning might be bad in some context (other programming languages)

## References

bash/zsh support it

**Comment by rgwood** [comment]
I can take this on. This is easy if we hardcode the functionality, I just need to figure out the best way to make it configurable.

One way would be to use Bash's HISTCONTROL and/or HISTIGNORE environment variables: 
- https://github.com/nushell/nushell/issues/6108
- https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-HISTCONTROL

I don't _love_ that approach, it gets into unpleasant "exactly how Bash-compatible does it need to be?" questions.

Another option: maybe we add a `history_ignore_prefix: Option<char>` to the Reedline struct? `None` by default, but users can configure it to be `Some(' ')` if they want.
