### ISSUE TITLE
In multiline commands from history, pressing 0 in vi normal mode jumps to the beginning of the last line.

### ISSUE THREAD

**Issue by boathouse2112** [nushell/reedline#582]
**Platform** e.g. macOS
**Terminal software** iterm2

Describe the problem you are observing.

When returning to a multiline input from history, pressing 0 in vi normal mode jumps to the beginning of the last line, even though the cursor shows at the end of the first line.

## Steps to reproduce
1. Submit multi-line input
2. Return to that input in the history, in vi normal mode
3. (optional) move the cursor around in the multi-line input -- issue will still occur
4. Press 0

## Screenshots/Screencaptures

https://github.com/nushell/reedline/assets/2874182/547c745f-3aaf-4a43-9e64-1e51284ca379

**Comment by fdncred** [comment]
with vi mode or emacs mode, this jumping has always been there. i'd love to see a fix for it.

**Comment by boathouse2112** [comment]
So the issue is in `engine.rs` > `Reedline.run_edit_commands`

```
if self.input_mode == InputMode::HistoryTraversal {
    if matches!(
        self.history_cursor.get_navigation(),
        HistoryNavigationQuery::Normal(_)
    ) {
        if let Some(string) = self.history_cursor.string_at_cursor() {
            self.editor
                .set_buffer(string, UndoBehavior::HistoryNavigation);
        }
    }
    self.input_mode = InputMode::Regular;
}
```

When it's called after moving around in the history, it replaces the current buffer, and when it does, the insertion point gets set to the end of the buffer, before the edit command is executed.

I'm not sure what reason there is for replacing the buffer with the current history cursor. Can it be removed?

**Comment by fdncred** [comment]
> Can it be removed?

I'm not sure. We'd have to see if the current tests pass (hopefully there's a test for such things) and it would be nice to have a new test to cover how it "should" work in the future. Another good thing about it that it can be tested in nushell too and see how it works in everyday life.
