### ISSUE TITLE
Select All shortcut with Ctrl A

### ISSUE THREAD

**Issue by max-programming** [nushell/reedline#622]
### Related problem

I am used to selecting and removing a command using `Ctrl + A` on the terminal. But I found that `nu` does not work in that case. Same issue is with GitBash and Command Prompt in my case. But it works good with Powershell

### Describe the solution you'd like

There should be a shortcut to select all with `Ctrl + A` or maybe another possible way to do that because right now `Ctrl + A` move the cursor to the start

**Comment by e-nikolov** [comment]
I made a [zsh plugin](https://github.com/e-nikolov/zsh-selections) that allows selections of the active line using `zle -w set-mark-command` and other zsh internals. Any idea if there is something comparable in nushell/reedline that can be used to make a similar plugin?

**Comment by fdncred** [comment]
select-all is supported in reedline now, as in, select all the text on the reedline commandline buffer. In nushell it's `ctrl-shift-a` but could be redefined to any supported key combination.
