### ISSUE TITLE
Using `SHIFT+ENTER` to enter newline instead of submitting command

### ISSUE THREAD

**Issue by savente93** [nushell/reedline#641]
As far as I can tell there's not really a convinient way to add a new line instead of submitting the current buffer. When I write scripts I'm usually executing them step by step in the terminal to see how they work, and not being able to add a newline is quite annoying. I would like a keybinding for insering an empty newline below my current cursor position.

My first idea was just `SHIFT+Enter` as that's how it works in quyite a few chat appliations such as Telegram, Teams, Slack etc. etc. I'm not aware if there are default keybindings for such a thing but if they do it would make sense to add those as well.

## References
Helix has a command for this (two actually, one for adding a newline above and one below the cursos) which I use all the time.  (documented here: https://docs.helix-editor.com/keymap.html#changes)

**Comment by fdncred** [comment]
In nushell you can provide a separate keybinding. This is what I do on my mac.
```
  {
    name: insert_newline
    modifier: alt
    keycode: enter
    mode: [emacs vi_normal vi_insert]
    event: { edit: insertnewline }
  }
```

**Comment by amtoine** [comment]
yeah i cannot get `shift + enter` to work on both Rio and Alacritty :confused: 

your keybinding works likes a charm though @fdncred :pray:

**Comment by savente93** [comment]
oeh that's a great one thanks! Do either of you think there is value in documenting it somewhere? (perhaps in the default config.nu?) or shall I just close this one?

**Comment by amtoine** [comment]
> oeh that's a great one thanks! Do either of you think there is value in documenting it somewhere? (perhaps in the default config.nu?) or shall I just close this one?
>
it looks to me this is question that comes up quite a lot, having that documented somewhere, maybe in the configuration section of the book, might be a great idea :+1: 

either way, if this is simply a matter of the terminal emulator being able to send `shift + enter` or not, we might want to close the issue, yes :yum:

**Comment by fdncred** [comment]
agreed
