### ISSUE TITLE
IDE style completions menu

### ISSUE THREAD

**Issue by universalmind303** [nushell/reedline#660]
microsoft just came out with a pretty cool IDE style completions menu for the CLI. 

It would be amazing to have this as a built in menu type. 

## References

https://github.com/microsoft/inshellisense

**Comment by fdncred** [comment]
yup, looking forward to someone submitting a PR to inshellisense to add nushell support. not exactly sure what reedline would need, if anything.

**Comment by universalmind303** [comment]
> yup, looking forward to someone submitting a PR to inshellisense to add nushell support. not exactly sure what reedline would need, if anything.

While it _could_ be done externally, I think a native IDE style menu type would greatly benefit the community as a whole. Many use reedline for creating text editors & other such toolings that would benefit from a built in ide style completion menu. 

The current Columnar and List menus work for many use cases, but I feel like the IDE style one is the main missing component.

**Comment by fdncred** [comment]
Yup, it would be a cool built-in. We just need a motivated and talented developer to implement it. You're welcome to try.

**Comment by HKalbasi** [comment]
Can this issue be closed now that there is `IdeMenu` after #696 ?

**Comment by fdncred** [comment]
yup, good point. thanks!
