### ISSUE TITLE
Incorrect resolution of cursor position

### ISSUE THREAD

**Issue by 101313** [nushell/reedline#685]
Alpinelinux, wayland, arm linux on apple silicon M1 

Describe the problem you are observing.

## Steps to reproduce
1. Have commandline -c executed on current buffer and read its value by any means.
eg: 
``` 
    {
        name: report_cursor_pos
        modifier: alt
        keycode: char_c
        mode: emacs
        event: { send: executehostcommand cmd: 'commandline -c' }
    }
```
And check the cursor position.

3. The implementation login is likely ignorant of lines and only counts letters.
In detail: For example  
![image](https://github.com/nushell/reedline/assets/99167477/987509a5-c1ce-4408-bab7-f4f37687081a)
While the same position would be reported as 2, 8 in text editors like vim.
![image](https://github.com/nushell/reedline/assets/99167477/720c65f4-a333-482b-bbfd-0eaf2831081e)

I would like to experiment with passing the cursor position to the editor upon opening the buffer editor so there is no longer a need for relocating the cursor to the correct position before starting editing inside the buffer editor.

**Comment by fdncred** [comment]
I don't think it's counting letters. It appears to be counting graphemes.

https://github.com/fdncred/nushell/blob/main/crates/nu-cli/src/commands/commandline.rs#L74-L88

Also, `commandline` is a nushell command, not reedline. This should probably be moved over.

**Comment by 101313** [comment]
Thanks for pointing it out @fdncred, I opened the respective issue at 
https://github.com/nushell/nushell/issues/11405
