### ISSUE TITLE
Unexpected spaces between the end of a pasted multiline string and reply

### ISSUE THREAD

**Issue by sigoden** [nushell/reedline#703]
**Platform** Ubuntu 22.04
**Terminal software** gnome-terminal

Unexpected spaces between the end of a pasted multiline string and reply.
The buffer also seems to be corrupted.

## Steps to reproduce
1. Run `cargo run --example demo`.
2. Paste multiline text whose height is more than the terminal height.

## Screenshots/Screencaptures

https://github.com/nushell/reedline/assets/4012553/b9741197-74b3-4b67-a04a-5a645ed891f8

![image](https://github.com/nushell/reedline/assets/4012553/95bbd750-3a59-427b-9582-69638b7d0a2a)

**Comment by chiefMarlin** [comment]
Any updates on this ?

**Comment by jacksongoode** [comment]
I think it might've actually been fixed. Maybe it would be good to bump reedline and see?
