### ISSUE TITLE
Refactor Menu System with Composition of Menu Functions

### ISSUE THREAD

**Issue by stormasm** [nushell/reedline#706]
#### columnar_menu.rs

```rust
    pub fn with_selected_text_style(mut self, selected_text_style: Style) -> Self {
        self.color.selected_text_style = selected_text_style;
        self
    }
```

#### list_menu.rs

```rust
   pub fn with_selected_text_style(mut self, selected_text_style: Style) -> Self {
        self.color.selected_text_style = selected_text_style;
        self
    }
```
#### ide_menu.rs

```rust
    pub fn with_selected_text_style(mut self, selected_text_style: Style) -> Self {
        self.color.selected_text_style = selected_text_style;
        self
    }
```

All three of our menu types have the exact same code in their implementations...

And this is true across all of our menu_functions lending itself to *massive* code duplication in our menu system.

As we continue to add new types of menus its only going to get worse, meaning in the future when we want to
refactor the menu system its going to be a lot more work...

Ideally we would compose this functionality so we only have one copy of the above code instead of three copies
and the composition style would lead to just adding new code for the functions that are unique to a particular menu
type.

**Comment by ysthakur** [comment]
To add on to this, `only_buffer_difference` is also handled pretty much the same way in all the menus, including `description_menu`, I think

**Comment by ysthakur** [comment]
I don't know if there's already a discussion going somewhere, but in case there isn't, I made a [HackMD](https://hackmd.io/@ysthakur/H1vZgA0Fp/edit) for brainstorming, would love to get more of your opinions @stormasm (cc: @maxomatic458, since you're working on improving completers) (also, just to clarify, I wasn't planning on making a PR all by myself anytime soon, just wanted to be involved in the discussion 🙂)

Moving the description menu into the same crate as the other menus makes sense to me too. Is there any reason to make a separate crate just for the `Menu` trait and its implementations, though? (I figured such a crate wouldn't be used by anyone other Reedline and Reedline users)

**Comment by stormasm** [comment]
I added your HackMd document here as well so it can be found easier in the next period of time...

https://hackmd.io/gDNAvI-8TDyubogworDyCA

**Comment by ysthakur** [comment]
Ah, a line-editor-agnostic menu system sounds cool

**Comment by maxomatic458** [comment]
> cc: @maxomatic458, since you're working on improving completers

im probably not making more changes to the completer anytime soon. I just added a function for convenience that menus can make use of.

All the menus also have a lot of fields in common (which could be compacted in a struct).

maybe we could also just get rid of the all the builder functions and use a proc macro for that?

**Comment by stormasm** [comment]
> > cc: @maxomatic458, since you're working on improving completers
> 
> im probably not making more changes to the completer anytime soon. I just added a function for convenience that menus can make use of.
> 
> All the menus also have a lot of fields in common (which could be compacted in a struct).
> 
> maybe we could also just get rid of the all the builder functions and use a proc macro for that?

I would probably 👎 the proc macro concept simply because longer term they are more difficult to read, understand, and maintain.

In my view, larger open source projects like nushell etc has lots of different people over time maintaining and reading the code and we should make it easy as possible for them to understand what is going on (including myself) 😄

**Comment by maxomatic458** [comment]
hmm i see,
so i guess we could do something like this then
```rs
struct MenuCommon {
    name: String,
    active: bool,
    // a bunch of fields that the menus share
}

// and then include this in the menus
struct Menu {
    common: MenuCommon,
    some_specific_thing_for_this_menu: ...
}
```
this would remove a good bit of code duplication, but then we would need two builders (one for the MenuCommon, and one for the menu itself) to build a menu
