### ISSUE TITLE
make the completer return the strings (or positions of them) that are used for completing

### ISSUE THREAD

**Issue by maxomatic458** [nushell/reedline#711]
I think this [the complete method](https://github.com/nushell/reedline/blob/d9db6a84b70d182c11c1a657d363c914eb3921d1/src/completion/base.rs#L32) could be changed, so it will also return the strings that were used to generate the Suggestions.

something like this:
```rs
fn complete(&mut self, line: &str, pos: usize) -> (Vec<Suggestion>, Vec<String>);
```

for example:
buffer: "this is t"
calling .complete could return the suggestions ("this is the reedline crate", "test", ...) alongside the strings that were used to calculate the suggestions (in this case "this is t", "t")

this info would be useful for menus (for example for greying out text already typed), or in the case of the new ide menu, change the position so it lines up with the typed text (instead of just the cursor)

**Comment by fdncred** [comment]
Seems plausible but sounds like it would be a breaking api change. Not that we're against that but seems like it may be tricky to retrofit in nushell. Maybe I'm wrong?

**Comment by maxomatic458** [comment]
i guess we could make a seperate function for this then, but i feel like this just makes things unnecessarily complicated

But if we would do that, then there wont be any breaking changes

**Comment by fdncred** [comment]
Separate function sounds great. If you put a //TODO in there around the function, to sometime consolidate functions, we can decide at a later point how important it is and if it's worth a breaking change. Thanks for bringing up this topic.

**Comment by maxomatic458** [comment]
to make this function "optional" then
should i have a default implementation that panics or returns default values, when its not explicitly implemented?

something like this
```rs
pub trait Completer: Send {
    /// the action that will take the line and position and convert it to a vector of completions, which include the
    /// span to replace and the contents of that replacement
    fn complete(&mut self, line: &str, pos: usize) -> Vec<Suggestion>;
    
    /// complete, but also return the index of the start of the string being completed
    fn complete_with_start(&mut self, line: &str, pos: usize) -> (Vec<Suggestion>, usize) {
        panic!("Not implemented")
    }
    ...
}
```

**Comment by fdncred** [comment]
Is it possible to have complete_with_start call complete if complete_with_start isn't implemented? Kind of uses the default implementation of complete if complete_with_start isn't implementd.

**Comment by maxomatic458** [comment]
@fdncred that would only work if we can assume that the suggestions starts with the last part of the line. then the start position can be calculated from that. otherwise (if the completer uses a different way, like levensthein distance of the last word or so)
then this will return a wrong value

but you could also return a default position like 0, but i think it would be better to panic then returning something potentially wrong

**Comment by maxomatic458** [comment]
all of the current menus that support this can just do this

```rs
impl Completer for DefaultCompleter {
    fn complete(&mut self, line: &str, pos: usize) -> Vec<Suggestion> {
        complete_with_start(&mut self, line: &str, pos: usize).0
    }
    
    fn complete_with_start(&mut self, line: &str, pos: usize) -> (Vec<Suggestion>, usize) {
        ...
    }
    ...
}
```

**Comment by fdncred** [comment]
I'm up for whatever. BTW - I've never really liked Levenstein completions. I always thought alphabetical was better.

**Comment by maxomatic458** [comment]
turns out each suggestion already includes the range in question.
so a base implementation does the trick
