### ISSUE TITLE
Is there an equivalent for `READLINE_LINE`, `READLINE_POINT ` and `READLINE_MARK` in Reedline?

### ISSUE THREAD

**Issue by giggio** [nushell/reedline#714]
I'm moving some scripts from Bash to Nushell and they use those variables to set content.

## References

See an example in the Navi widget:

https://github.com/denisidoro/navi/blob/c45b767edd1c751691d353622ae0ad7336f94ab7/shell/navi.plugin.bash#L24-L25

When you press CTRL-G in Navi you get to choose a command. That command is then ran and added to the history, and that snippet is how they do it. Earlier they read from it, too, to start the command search.

See more context:
https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html
https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html

**Comment by fdncred** [comment]
I don't think so. I know of no command that runs a command puts it in the history. The closes we have in nushell is the `commandline` command that just manipulates the command line buffer.

**Comment by giggio** [comment]
Is there any way to get what was typed by the user before they entered a command like CTRL_G?

**Comment by fdncred** [comment]
commandline gets the buffer

**Comment by giggio** [comment]
> commandline gets the buffer

That worked. Thanks!

https://github.com/giggio/nuscripts/blob/c77bbcf7b2ca422534f8ccf0f0cd3a84f2b0a4cd/scripts/navi.nu#L6

Now, I only need one thing to finish that widget for Navi. I'm using the keybinding with `ExecuteHostCommand`. If the user presses ESC, I still get a new line on the prompt. Is there a way to go back to where the user was, without triggering a new line?

Sorry about asking this here, but there the discussions are not enabled on the repo.

**Comment by fdncred** [comment]
We trigger newline too often imo. I don't know of a way to avoid it. The only thing I've seen that doesn't add a newline is my abbr menu and keybinding, so menus may not cause the newline like keybindings.

**Comment by giggio** [comment]
Should I open an issue about it? I'll close this one.
