### ISSUE TITLE
IDE menu should allow a max number of items

### ISSUE THREAD

**Issue by universalmind303** [nushell/reedline#719]
Let us know about features you really want to see in reedline. 

Specifying a max number of displayed items can make the menus a bit more readable on smaller terminals. 

If a max is specified, <kbd>TAB</kbd>/<kbd>DOWN</kbd>/<kbd>UP</kbd> should continue scrolling to the next items when the max is reached 
## References

something like this, but nicer and not buggy. 

https://github.com/nushell/reedline/assets/21327470/290a7de3-3f69-4faf-b34a-e6b5111e7e53

**Comment by maxomatic458** [comment]
@universalmind303 if you look at the ide_completion exapmles, there is a config value called "max_completion_height" that should do what you want
