### ISSUE TITLE
add "typed-text-style" to MenuTextStyle 

### ISSUE THREAD

**Issue by maxomatic458** [nushell/reedline#724]
this is a concept from the nushell discord by "bisaknosp"
![grafik](https://github.com/nushell/reedline/assets/104733404/9e80d102-c1ac-40c9-8484-3c12c0ed1bf3)

https://github.com/nushell/reedline/blob/03a1baba6c2403e172e7eb1d4ad0c3175376c916/src/menu/mod.rs#L16-L23

**Comment by fdncred** [comment]
I could see where that may be helpful.
