### ISSUE TITLE
list menu marker changing color

### ISSUE THREAD

**Issue by maxomatic458** [nushell/reedline#727]
windows 10; windows terminal.

https://github.com/nushell/reedline/assets/104733404/bb9b1fce-e061-4cb6-a1ce-19f86bbbd9eb

**Comment by fdncred** [comment]
I'm missing the point here. what is changing colors?

**Comment by maxomatic458** [comment]
@fdncred the marker changes color to white, when the selection is at the bottom of the terminal

is that intended?

**Comment by fdncred** [comment]
oh, i see it now. nope, that's not intended. not sure why it's doing that. good eye!

**Comment by ysthakur** [comment]
Looks like `print_small_buffer` has this bit of code before printing the prompt indicator, but not `print_large_buffer`:
```rust
        if use_ansi_coloring {
            self.stdout
                .queue(SetForegroundColor(prompt.get_indicator_color()))?;
        }
```

**Comment by fdncred** [comment]
thanks for fixing this!
