### ISSUE TITLE
Columnar Menu does not truncate the description, leading to weird prompt rendering

### ISSUE THREAD

**Issue by maxomatic458** [nushell/reedline#738]
video clip from @fdncred https://github.com/nushell/nushell/pull/11670#issuecomment-1920245280

the description of str substring is to long to fit in a line, which seems to be the cause of this

**Comment by fdncred** [comment]
Sincerely thanks so much for investigating and creating this issue!!! ❤️ 

I've tested it on Windows and it has similar but slightly different behavior.
![completions](https://github.com/nushell/reedline/assets/343840/d7c296c4-c53a-4aae-9561-4950d10d7944)

**Comment by maxomatic458** [comment]
It might actually be caused by my PR
Im investigating it right now
