### ISSUE TITLE
odd moving of text when on bottom row of terminal

### ISSUE THREAD

**Issue by fdncred** [nushell/reedline#76]
this is hard to describe but it appears that in Windows using Windows Terminal, when you're on the bottom row of the terminal and you type something like 'now is the time for all good men' and hit enter, it briefly moves the text ~10 characters to the right, then accepts the text and prints it as normal. It's really odd and hard to explain.

I reproduce this by doing:
1. clear
2. cargo clean
3. cargo run
4. ls <enter>
5. now is the time for all good men<enter>
6. and watch it shift and then accept

i've tried to capture it with screentogif but i'm not able to.

ok, here's what it's doing. i changed screentogif to run at 60 fps and i caught the error. here are the 3 frames.

frame 1 - when i typed in some (any) text
![image](https://user-images.githubusercontent.com/343840/123157437-28070700-d430-11eb-81fc-8bf3c0bb9595.png)

frame2 - the flashing that i see, which i characterized above as ~10 chars to the right. it actually is moving the text to the right because it's prefixed by `Our buffer: `
![image](https://user-images.githubusercontent.com/343840/123157567-4d941080-d430-11eb-92e9-50dd81518c32.png)

frame3 - when it accepts the text
![image](https://user-images.githubusercontent.com/343840/123157617-61d80d80-d430-11eb-94ad-bd6f6ac30ac7.png)

**Comment by sholderbach** [comment]
Triage: Has this been resolved on Windows by the fixes from #77?

**Comment by stormasm** [comment]
Same exact issue on the Mac as described in #132

**Comment by fdncred** [comment]
@sholderbach I haven't tested recently. Feel free to close this issue if you think it's fixed by #77.

**Comment by stormasm** [comment]
@fdncred @sholderbach this issue is not fixed on the mac...

**Comment by fdncred** [comment]
oh, @stormasm, I thought you were saying that issue #132 wasn't fixed on the mac. Sorry.

**Comment by stormasm** [comment]
@fdncred yep ---- sorry about that ---- I should have been more clear...

**Comment by sholderbach** [comment]
Probably out of date, painting logic and handling of the bottom of the screen case was changed significantly with #217
