### ISSUE TITLE
analog to inputrc for programs using reedline

### ISSUE THREAD

**Issue by Konfekt** [nushell/reedline#797]
[Python's REPL](https://docs.python.org/3/library/readline.html) uses `.inputrc` for customized bindings. It would be helpful to know where programs using reedline by default read their customized bindings.
The documented [example](https://docs.rs/reedline/latest/reedline/) seems directed to a developer rather than a user.

**Comment by fdncred** [comment]
Keybindings are hard coded unless the application using reedline exposes a file for customization. This is what nushell does.
