### ISSUE TITLE
`oh-my-posh` left and right prompt are not drawn at the same level

### ISSUE THREAD

**Issue by Schweber** [nushell/reedline#804]
I want to have the left and the right prompt at the same level at all times. However, the right prompt is drawn one line above as soon as the prompt is redrawn for the first time:

![image](https://github.com/nushell/reedline/assets/64630479/7dc9eaac-2971-4efd-9666-b4ed8f1187d7)

It worked before the update to nushell v0.95, could this have introduced this behavior?

Please see [this](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/5191#discussioncomment-9928408) issue in `oh-my-posh`.

| key | value |
| --- | --- |
| version            | 0.95.0                                                            |
| major              | 0                                                                 |
| minor              | 95                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball) |
| cargo_version      | cargo 1.78.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
What happens if you change this setting in the config.nu `render_right_prompt_on_last_line`?

**Comment by sholderbach** [comment]
Still curious why it appeared above and setting it to `true` fixed it. I thought the idea of the setting was that it takes effect when your input/prompt gets longer than one line to keep the right prompt out of the way or if `false` at the same height as the left prompt.
