### ISSUE TITLE
clear_screen to fit in Warp's manner

### ISSUE THREAD

**Issue by tisonkun** [nushell/reedline#811]
Warp always has an upper block for the last command:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/9ffce1c5-a7eb-4ea0-b414-2f286197a95d">

Currently, Reedline's `clear_screen` will print empty lines to move the current insert point to the most upper position, which is hidden by the block quoted.

I don't know how `mysql` can "clear screen" (ctrl+l) properly as shown above, but this can be a compatibility request.

**Comment by tisonkun** [comment]
rustyline's implementation uses `self.write_and_flush("\x1b[H\x1b[J")` and it seems work.

**Comment by fdncred** [comment]
you can try that out with keybindings to see if that makes a difference with `$"(ansi cursor_home)(ansi clear_screen)"`

**Comment by tisonkun** [comment]
@fdncred I saw the custom keybindings right now but I'm wondering what to put here ...

```rust
    let mut keybindings = reedline::default_emacs_keybindings();
    keybindings.add_binding(
        reedline::KeyModifiers::CONTROL,
        reedline::KeyCode::Char('l'),
        todo!("not yet find the effect alternative clear_screen impl"),
    );

    let mut state = Reedline::create()
        .with_validator(Box::new(..))
        .with_highlighter(Box::new(..))
        .with_edit_mode(Box::new(Emacs::new(keybindings)));
```

**Comment by tisonkun** [comment]
Perhaps `EditCommand`, but I don't interact with the buffer, I'd talk to the `painter`.

**Comment by fdncred** [comment]
I was giving you nushell commands to try, sorry. 

It looks like the reedline `clear_screen` function isn't quite working like rustyline's.
```rust
    pub(crate) fn clear_screen(&mut self) -> Result<()> {
        self.stdout.queue(cursor::Hide)?;
        let (_, num_lines) = terminal::size()?;
        for _ in 0..2 * num_lines {
            self.stdout.queue(Print("\n"))?;
        }
        self.stdout.queue(MoveTo(0, 0))?; # This is go to home
        self.stdout.queue(cursor::Show)?;

        self.stdout.flush()?;
        self.initialize_prompt_position()
    }
```

Seems like it might should be closer to the `clear_scrollback` function but without the purge.
```rust
    pub(crate) fn clear_scrollback(&mut self) -> Result<()> {
        self.stdout
            .queue(crossterm::terminal::Clear(ClearType::All))?
            .queue(crossterm::terminal::Clear(ClearType::Purge))?
            .queue(cursor::MoveTo(0, 0))?
            .flush()?;
        self.initialize_prompt_position()
    }
```

**Comment by fdncred** [comment]
To mimic rustline you'd have to use `MoveTo(0, 0)` and then `ClearType::FromCursorDown`.

**Comment by tisonkun** [comment]
> to fix the clear_screen function or add another one as suggested above

This should happen within reedline (so a PR). Does it what you mean ;D?

**Comment by fdncred** [comment]
If you want it to work like rustyline, `ClearType::All` is the wrong enum. It should be `ClearType::FromCursorDown`.

**Comment by sholderbach** [comment]
History time: that we print those newlines is down to my second PR ever to reedline in #30, basically the goal was to replicate the `Ctrl-L` behavior from bash in a somewhat faithful manner (#28). 
`^L` is equivalent to form-feed in ASCII so should not delete any existing content but only move that off the screen and redraw the prompt at the top of the visible area.

Not sure if `\e[2J` or `\e[J` is the right one I have seen [mentions of both](https://askubuntu.com/questions/434240/ctrll-in-terminal).

Our `ClearScreen` should in my view do the same as the [bash `clear-screen`](https://www.man7.org/linux/man-pages/man3/readline.3.html)/`Ctrl-L` and not be the same as `clear-display`

**Comment by tisonkun** [comment]
@sholderbach Thanks for the background!

I typically have a few options to start a PR for discussions:

1. Replace `clear_screen` entirely, which may cause compatibility issues with all historical considerations.
2. Switch the manner with a feature flag, but it looks like random changes.
3. Add a new `ReedlineEvent` perhaps called `ClearDisplay` and allow users to rebind the keybindings as I try above (we just cannot directly talk to the painter).
4. Try to determine the terminal type and use a proper implementation.

I'll send a PR first adopt 3 and see if we can reach 4.
